#!/usr/bin/env bash

#
#  Copyright (C) 2018 Hortonworks Inc.
#
#  Licenced under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

if [ "x${DTEST_HOME}" = "x" ]
  then
  export DTEST_HOME="."
fi

if [ "x${DTEST_LOG_DIR}" = "x" ]
  then
  export DTEST_LOG_DIR=${DTEST_HOME}/log
fi

if [ "x${JAVA_HOME}" = "x" ]
  then
  JAVA_HOME="/usr"
fi

CLASSPATH="${DTEST_HOME}/conf"

for f in ${DTEST_HOME}/lib/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done

$JAVA_HOME/bin/java -cp $CLASSPATH -Dlog4j.configurationFile=${DTEST_HOME}/conf/log4j2.xml \
    -Ddtest.core.buildinfo.basedir=${DTEST_LOG_DIR} org.dtest.core.DockerTest "$@"
