#!/usr/bin/env bash

#
#  Copyright (C) 2018 Hortonworks Inc.
#
#  Licenced under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

if [ "x${DTEST_HOME}" = "x" ]
  then
  export DTEST_HOME="."
fi

if [ "x${JAVA_HOME}" = "x" ]
  then
  JAVA_HOME="/usr"
fi

CLASSPATH="${DTEST_HOME}/conf"

for f in ${DTEST_HOME}/lib/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done

# Find the build directory and set the DTEST_BUILD_DIR so that the log4j logfile ends up in the right place.
# Also find any Java properties that were passed in and pass them to Java instead of to DockerTest
dirNext="false"
PROPS=""
export DTEST_BUILD_DIR="/tmp"  # Preset it to tmp in case it isn't set
for arg in $@
do
  if [ $dirNext = "true" ]
    then
    export DTEST_BUILD_DIR=$arg
    dirNext="false"
  else
    case $arg in
      -d | --build-dir)
        dirNext="true"
        ;;

      -D*)
        PROPS="$PROPS $arg"
        ;;
    esac
  fi
done

$JAVA_HOME/bin/java -cp $CLASSPATH -Dlog4j.configurationFile=${DTEST_HOME}/conf/log4j2.xml \
    $PROPS org.dtest.core.DockerTest "$@"
