#!/usr/bin/env bash

#
#  Copyright (C) 2018 Hortonworks Inc.
#
#  Licenced under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

if [ "x${DTEST_HOME}" = "x" ]
  then
  DTEST_HOME="."
fi

if [ "x${JAVA_HOME}" = "x" ]
  then
  JAVA_HOME="/usr"
fi

CLASSPATH="${DTEST_HOME}/conf"

for f in ${DTEST_HOME}/lib/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done

ARGS=()
PROPERTIES=()
while [ $# -gt 0 ]; do
  IS_PROP=`echo $1 | egrep "^-Ddtest\."`
  if [[ "x${IS_PROP}" != "x" ]]
  then
    PROPERTIES=("${PROPERTIES[@]}" "$1")
  else
    ARGS=("${ARGS[@]}" "$1")
  fi
  shift
done

$JAVA_HOME/bin/java -cp $CLASSPATH "${PROPERTIES[@]}" \
    -Dlog4j.configurationFile=${DTEST_HOME}/conf/dtest-log4j2.properties \
    org.dtest.core.DockerTest "${ARGS[@]}"
